function FileData_Pairs(x)
{
x.t("debugging","mode");
x.t("debugging","programs");
x.t("debugging","send");
x.t("debugging","configure");
x.t("debugging","using");
x.t("protected","u.s");
x.t("studio","enable");
x.t("studio","live");
x.t("u.s","international");
x.t("mode","configure");
x.t("support","1998-2009");
x.t("international","intellectual");
x.t("product","protected");
x.t("product","covered");
x.t("property","laws");
x.t("listed","patent.txt");
x.t("file","found");
x.t("found","http://www.vmware.com/go/patents");
x.t("intellectual","property");
x.t("programs","configure");
x.t("laws","product");
x.t("vmware","product");
x.t("enable","live");
x.t("technical","support");
x.t("visual","studio");
x.t("send","feedback");
x.t("1998-2009","vmware");
x.t("live","debugging");
x.t("configure","visual");
x.t("patent.txt","file");
x.t("feedback","technical");
x.t("using","live");
x.t("covered","patents");
x.t("patents","listed");
}
