function FileData_Pairs(x)
{
x.t("debugging","tips");
x.t("debugging","mode");
x.t("debugging","replay");
x.t("protected","u.s");
x.t("experience","following");
x.t("u.s","international");
x.t("tips","experience");
x.t("tips","replay");
x.t("tips","troubleshooting");
x.t("errors","debugging");
x.t("mode","send");
x.t("support","1998-2009");
x.t("international","intellectual");
x.t("product","protected");
x.t("product","covered");
x.t("property","laws");
x.t("listed","patent.txt");
x.t("file","found");
x.t("found","http://www.vmware.com/go/patents");
x.t("intellectual","property");
x.t("common","errors");
x.t("laws","product");
x.t("vmware","product");
x.t("technical","support");
x.t("replay","debugging");
x.t("troubleshooting","live");
x.t("send","feedback");
x.t("1998-2009","vmware");
x.t("live","replay");
x.t("patent.txt","file");
x.t("feedback","technical");
x.t("following","common");
x.t("covered","patents");
x.t("patents","listed");
}
